### ISSUE TITLE
Name of nrf52832 crate is still nrf52

### ISSUE THREAD

**Issue by hannobraun** [jamesmunns/nrf52#10]
See Cargo.toml: https://github.com/nrf-rs/nrf52832/blob/3d30fa6eb904a20cde5f5df2d6e27857bca14091/nrf52832/Cargo.toml#L12

**Comment by jonas-schievink** [comment]
This is fixed now, but the [`nrf52`](https://crates.io/crates/nrf52) crate still exists. We can push an empty crate directing to the `nrf52832-pac` crate.

**Comment by jonas-schievink** [comment]
Published [`nrf52`](https://crates.io/crates/nrf52) version 0.4.1, which adds deprecation warnings
