### ISSUE TITLE
Use mainstream svd2rust

### ISSUE THREAD

**Issue by wez** [jamesmunns/nrf52#3]
In https://github.com/jamesmunns/nrf52/pull/2 I changed our update.sh script to reference my fork of svdrust.  My fork is based on the current release plus the following:

https://github.com/rust-embedded/svd2rust/pull/193
https://github.com/japaric/svd/issues/57
+ a series of PRs in svd that have landed but have not been released; svd-parser has not been updated in 6 months due to the focus on https://github.com/japaric/svd/pull/53

Once those are unblocked, we can switch back to the official svd2rust release.

**Comment by jonas-schievink** [comment]
This is done, we're using svd2rust 0.16.1 now.
