### ISSUE TITLE
[RFC] Rename repo to nrf-pac

### ISSUE THREAD

**Issue by wez** [jamesmunns/nrf52#7]
Transplanting the thread from here https://github.com/nrf-rs/nrf52832/pull/5

> I'd suggest renaming this repo to a more generic name. Locally I have a `nrf52-svd` checkout of this repo, but if we're also likely to end up with nrf51 in here too, perhaps we should pre-empt that and name it `nrf-svd` or `nrf-peripherals` or something a little more broad?
> 
> cc: @jscarrott, @therealprof, @jamesmunns, @hannobraun

@hannobraun:
> Some thoughts about name: I don't like `nrf-svd`. These crates are about providing low-level access to peripherals. The SVDs are just an implementation detail. Also not a fan of `nrf-peripheral`, as that's quite generic and at the same time quite long.
> 
> How about:
> 
>   * `nrf`: Very generic, but also very short.
> 
>   * `nrf-pac`: The phrase "peripheral access crate" is already established in the Rust community. We could forge ahead and try to establish `-pac` as the de-facto prefix for those crates (there's even [some prior art](https://www.google.com/search?q=%22peripheral+access+crate%22+%22pac%22)).
> 
> 
> I currently prefer `nrf-pac`, but I would be fine with all other suggestions, too.

@wez:
> I'd prefer having some kind of suffix to the name to make it harder to get confused about which repo/create I'm looking at. I'm on-board with `nrf-pac`, but let's see what the others think about this before renaming the repo.

**Comment by jonas-schievink** [comment]
So it seems like c3b33c852f6f13fdc4fd15b2e46c2ba50f71f69b reverted back to only hosting the nRF52832, right? In that case, should this be closed?

**Comment by Yatekii** [comment]
Uhm we support all 3 current nRF52. There is a 4th one comming (nRF52811 with the 802.15.4 radio but an M4-NoHF and less peripherals, just like the nRF52810 is to the nRF52832.

**Comment by jamesmunns** [comment]
@Yatekii I did split off the various pac crates. They are all in this organization, but not this repo.

I'd be okay with combining them if someone puts it together, or we can close this repo.

**Comment by Yatekii** [comment]
Oh, mea culpa, nvm me. I am fine with how it is atm tbh. So I think we can close this issue.

**Comment by hannobraun** [comment]
I'd prefer to have all PACs in one repository, but that preference is too weak to justify any action :-)

I'm fine with closing this.

**Comment by jamesmunns** [comment]
Okay, closing this for now, but I want to make sure it is known that we are not against the idea, and if someone is willing to submit a PR (or a new repo) that combines all of the PACs, it would be welcome.

Feel free to refer to this issue in the future.
